import {Component,inject} from '@angular/core';
import {FormBuilder,ReactiveFormsModule,Validators} from '@angular/forms';
import {MatButtonModule} from '@angular/material/button';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatIconModule} from '@angular/material/icon';
import {MatInputModule} from '@angular/material/input';
import {MatSnackBar,MatSnackBarModule} from '@angular/material/snack-bar';
import {Router,RouterLink} from '@angular/router';
import {AuthService} from './auth.service';

@Component({selector:'app-login-page',standalone:true,imports:[RouterLink,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSnackBarModule],template:`<section class="auth-layout"><div class="auth-art"><a class="brand-large" routerLink="/"><span class="brandmark"><mat-icon>restaurant</mat-icon></span>EatHealthy</a><div><span class="eyebrow">Welcome back</span><h1>Your healthy routine is waiting.</h1><p>Pick up your meal schedule, record today’s progress and keep moving toward your goal.</p></div></div><div class="auth-panel"><form [formGroup]="form" (ngSubmit)="submit()"><h2>Sign in</h2><p>Use your EatHealthy account to continue.</p><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"></mat-form-field><mat-form-field appearance="outline"><mat-label>Password</mat-label><input matInput type="password" formControlName="password"></mat-form-field><button mat-flat-button type="submit">Sign in</button><div class="demo-note"><b>Admin preview</b><span>admin@eathealthy.co.za · Password1!</span></div><p class="auth-switch">New here? <a routerLink="/register">Create an account</a></p></form></div></section>`})
export class LoginPageComponent{private fb=inject(FormBuilder);private auth=inject(AuthService);private router=inject(Router);private snack=inject(MatSnackBar);form=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]],password:['',[Validators.required,Validators.minLength(6)]]});submit(){if(this.form.invalid)return;if(this.auth.signIn(this.form.getRawValue().email,this.form.getRawValue().password))this.router.navigateByUrl(this.auth.isAdmin()?'/admin':'/planner');else this.snack.open('Check your email and password.','Close',{duration:3000})}}

@Component({selector:'app-register-page',standalone:true,imports:[RouterLink,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule],template:`<section class="auth-layout"><div class="auth-art register-art"><a class="brand-large" routerLink="/"><span class="brandmark"><mat-icon>restaurant</mat-icon></span>EatHealthy</a><div><span class="eyebrow">Begin with what you know</span><h1>A healthier plan, built around your life.</h1><p>Create your account, then tell us about your goals, food preferences and budget.</p></div></div><div class="auth-panel"><form [formGroup]="form" (ngSubmit)="submit()"><h2>Create your account</h2><p>It only takes a minute to get started.</p><mat-form-field appearance="outline"><mat-label>Full name</mat-label><input matInput formControlName="name"></mat-form-field><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"></mat-form-field><mat-form-field appearance="outline"><mat-label>Password</mat-label><input matInput type="password" formControlName="password"></mat-form-field><mat-form-field appearance="outline"><mat-label>Confirm password</mat-label><input matInput type="password" formControlName="confirm"></mat-form-field><button mat-flat-button type="submit">Create account</button><p class="auth-switch">Already registered? <a routerLink="/login">Sign in</a></p></form></div></section>`})
export class RegisterPageComponent{private fb=inject(FormBuilder);private auth=inject(AuthService);private router=inject(Router);form=this.fb.nonNullable.group({name:['',Validators.required],email:['',[Validators.required,Validators.email]],password:['',[Validators.required,Validators.minLength(6)]],confirm:['',Validators.required]});submit(){const v=this.form.getRawValue();if(this.form.invalid||v.password!==v.confirm)return;this.auth.register(v.name,v.email);this.router.navigateByUrl('/onboarding')}}

@Component({selector:'app-onboarding-page',standalone:true,imports:[ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatInputModule],template:`<section class="onboarding page-pad"><div class="section-heading"><span class="eyebrow">Complete your profile</span><h1>Help us shape a plan that fits you.</h1><p>We’ll ask you to update your weight every two weeks so progress stays meaningful.</p></div><form class="surface-form onboarding-form" [formGroup]="form" (ngSubmit)="submit()"><div class="avatar-upload"><span>BR</span><div><b>Profile picture</b><small>Photo upload will use Cloudinary when connected.</small></div><button mat-stroked-button type="button">Choose photo</button></div><mat-form-field appearance="outline"><mat-label>Preferred name</mat-label><input matInput formControlName="name"></mat-form-field><mat-form-field appearance="outline"><mat-label>Age</mat-label><input matInput type="number" formControlName="age"></mat-form-field><mat-form-field appearance="outline"><mat-label>Current weight (kg)</mat-label><input matInput type="number" formControlName="current"></mat-form-field><mat-form-field appearance="outline"><mat-label>Target weight (kg)</mat-label><input matInput type="number" formControlName="target"></mat-form-field><button mat-flat-button type="submit">Save and build my plan</button></form></section>`})
export class OnboardingPageComponent{private fb=inject(FormBuilder);private auth=inject(AuthService);private router=inject(Router);form=this.fb.nonNullable.group({name:[this.auth.user()?.name||'',Validators.required],age:[30,Validators.required],current:[85,Validators.required],target:[78,Validators.required]});submit(){if(this.form.invalid)return;this.auth.completeOnboarding(this.form.getRawValue().name);this.router.navigateByUrl('/planner')}}
