import {CommonModule} from '@angular/common';
import {Component,inject,signal} from '@angular/core';
import {MatButtonModule} from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import {MatProgressBarModule} from '@angular/material/progress-bar';
import {MatSlideToggleModule} from '@angular/material/slide-toggle';
import {RouterLink} from '@angular/router';
import {AuthService} from './auth.service';

@Component({selector:'app-schedules-page',standalone:true,imports:[CommonModule,RouterLink,MatButtonModule,MatIconModule,MatProgressBarModule],template:`<section class="member-page page-pad"><div class="page-title"><div><span class="eyebrow">Today · Wednesday</span><h1>Your meal schedule</h1><p>Complete each meal in its planned window or record what got in the way.</p></div><a mat-flat-button routerLink="/planner">Create a new plan</a></div><div class="schedule-summary"><article><span>Today’s progress</span><b>2 of 4 meals</b><mat-progress-bar mode="determinate" [value]="50"></mat-progress-bar></article><article><span>Daily target</span><b>1,850 kcal</b><small>920 kcal recorded</small></article><article><span>Current streak</span><b>4 days</b><small>Keep it going</small></article></div><div class="schedule-list">@for(meal of meals;track meal.time){<article [class.done]="meal.done"><div class="schedule-time">{{meal.time}}</div><div class="meal-icon"><mat-icon>{{meal.icon}}</mat-icon></div><div><span>{{meal.type}}</span><h3>{{meal.name}}</h3><p>{{meal.calories}} kcal · {{meal.note}}</p></div><div class="schedule-actions"><a mat-icon-button [href]="meal.video" target="_blank" aria-label="Watch recipe"><mat-icon>play_circle</mat-icon></a><button mat-stroked-button (click)="meal.done=!meal.done">{{meal.done?'Completed':'Mark done'}}</button></div></article>}</div></section>`})
export class SchedulesPageComponent{meals=[{time:'06:30',type:'Breakfast',name:'Oats, banana & peanut butter',calories:410,note:'high fibre',icon:'breakfast_dining',video:'https://www.youtube.com/results?search_query=healthy+oats+banana',done:true},{time:'10:30',type:'Snack',name:'Apple & plain yoghurt',calories:190,note:'quick and familiar',icon:'apple',video:'https://www.youtube.com/results?search_query=healthy+yoghurt+snack',done:true},{time:'12:30',type:'Lunch',name:'Chicken, potato & vegetables',calories:520,note:'38g protein',icon:'lunch_dining',video:'https://www.youtube.com/results?search_query=healthy+chicken+potato+vegetables',done:false},{time:'18:30',type:'Dinner',name:'Pilchard tomato rice bowl',calories:490,note:'budget friendly',icon:'dinner_dining',video:'https://www.youtube.com/results?search_query=pilchard+rice+bowl',done:false}]}

@Component({selector:'app-profile-page',standalone:true,imports:[MatButtonModule,MatIconModule,MatProgressBarModule,MatSlideToggleModule],template:`<section class="member-page page-pad"><div class="page-title"><div><span class="eyebrow">Your account</span><h1>Profile & progress</h1><p>Keep your details current so recommendations remain relevant.</p></div><button mat-flat-button>Save changes</button></div><div class="profile-grid"><article class="profile-card"><div class="profile-avatar">{{initials}}</div><h2>{{auth.user()?.name}}</h2><p>{{auth.user()?.email}}</p><span class="role-pill">{{auth.user()?.role}}</span><button mat-stroked-button>Change photo</button></article><article class="progress-card"><span>FORTNIGHTLY CHECK-IN</span><h2>85.0 kg → 78.0 kg</h2><p>Next weight update due in 4 days.</p><mat-progress-bar mode="determinate" [value]="34"></mat-progress-bar><div class="metric-row"><div><small>Started</small><b>88.2 kg</b></div><div><small>Progress</small><b>3.2 kg</b></div><div><small>Projected</small><b>82.4 kg</b></div></div><button mat-flat-button>Update my weight</button></article><article class="settings-card"><h2>Preferences</h2><label><span><b>Email reminders</b><small>Meals, check-ins and reports</small></span><mat-slide-toggle checked></mat-slide-toggle></label><label><span><b>Health professional prompt</b><small>Suggest help when progress stalls</small></span><mat-slide-toggle checked></mat-slide-toggle></label></article></div></section>`})
export class ProfilePageComponent{auth=inject(AuthService);get initials(){return this.auth.user()?.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()||'EH'}}

@Component({selector:'app-notifications-page',standalone:true,imports:[MatButtonModule,MatIconModule],template:`<section class="member-page narrow-page page-pad"><div class="page-title"><div><span class="eyebrow">Stay on track</span><h1>Notifications</h1><p>Meal reminders, account notices and progress prompts in one place.</p></div><button mat-stroked-button>Mark all read</button></div><div class="notification-list"><article class="unread"><mat-icon>lunch_dining</mat-icon><div><span>MEAL REMINDER · NOW</span><h3>Lunch is planned for 12:30</h3><p>Chicken, potato and vegetables · 520 kcal. Snooze for 15 minutes or mark it complete.</p></div><button mat-icon-button><mat-icon>more_horiz</mat-icon></button></article><article class="unread"><mat-icon>monitor_weight</mat-icon><div><span>PROGRESS · 4 DAYS</span><h3>Your fortnightly check-in is coming up</h3><p>Update your weight to see whether the current plan is moving you toward your goal.</p></div></article><article><mat-icon>payments</mat-icon><div><span>SUBSCRIPTION · 28 AUG</span><h3>Your Plus trial ends soon</h3><p>Review your plan before access changes to the free tier.</p></div></article><article><mat-icon>insights</mat-icon><div><span>WEEKLY REPORT</span><h3>You completed 78% of planned meals</h3><p>Breakfast was your strongest habit. Dinner needs a little more consistency.</p></div></article></div></section>`}) export class NotificationsPageComponent{}

@Component({selector:'app-reports-page',standalone:true,imports:[MatButtonModule,MatIconModule,MatProgressBarModule],template:`<section class="member-page page-pad"><div class="page-title"><div><span class="eyebrow">Your consistency</span><h1>Reports</h1><p>A simple view of what worked, what was missed and where to adjust.</p></div><button mat-stroked-button><mat-icon>download</mat-icon>Export report</button></div><div class="report-kpis"><article><span>Completion rate</span><b>78%</b><small>+9% from last week</small></article><article><span>Meals completed</span><b>22/28</b><small>3 late · 3 missed</small></article><article><span>Weight trend</span><b>−1.4 kg</b><small>Over the last 30 days</small></article><article><span>Budget estimate</span><b>R2,380</b><small>R120 below target</small></article></div><div class="report-panel"><h2>Weekly adherence</h2>@for(day of days;track day.name){<div class="bar-row"><span>{{day.name}}</span><mat-progress-bar mode="determinate" [value]="day.value"></mat-progress-bar><b>{{day.value}}%</b></div>}<div class="report-insight"><mat-icon>lightbulb</mat-icon><p><b>Your strongest pattern:</b> breakfast completion is consistently high. Consider preparing dinner ingredients earlier to reduce evening misses.</p></div></div></section>`}) export class ReportsPageComponent{days=[{name:'Mon',value:100},{name:'Tue',value:75},{name:'Wed',value:50},{name:'Thu',value:100},{name:'Fri',value:75},{name:'Sat',value:50},{name:'Sun',value:100}]}

@Component({selector:'app-admin-page',standalone:true,imports:[MatButtonModule,MatIconModule],template:`<section class="member-page page-pad"><div class="page-title"><div><span class="eyebrow">Administrator</span><h1>Platform overview</h1><p>Monitor members, plans, subscriptions and operational follow-ups.</p></div><button mat-flat-button><mat-icon>person_add</mat-icon>Add team member</button></div><div class="admin-kpis"><article><mat-icon>group</mat-icon><span>Active members</span><b>1,248</b><small>+84 this month</small></article><article><mat-icon>restaurant_menu</mat-icon><span>Plans generated</span><b>3,906</b><small>412 this week</small></article><article><mat-icon>payments</mat-icon><span>Active subscriptions</span><b>426</b><small>34% conversion</small></article><article><mat-icon>support_agent</mat-icon><span>Dietitian referrals</span><b>18</b><small>5 need follow-up</small></article></div><div class="admin-table"><div class="table-heading"><h2>Recent members</h2><button mat-button>View all</button></div><table><thead><tr><th>Member</th><th>Plan</th><th>Progress</th><th>Subscription</th><th>Status</th></tr></thead><tbody><tr><td>BK Radipabe</td><td>Weight loss · 14 days</td><td>−3.2 kg</td><td>Plus</td><td><span class="status-good">On track</span></td></tr><tr><td>Naledi M.</td><td>Maintain · 7 days</td><td>No check-in</td><td>Free</td><td><span class="status-warn">Follow up</span></td></tr><tr><td>Thabo K.</td><td>Weight loss · 10 days</td><td>0 kg</td><td>Guided trial</td><td><span class="status-warn">Referral</span></td></tr></tbody></table></div></section>`}) export class AdminPageComponent{}
