import {Component} from '@angular/core';
import {MatButtonModule} from '@angular/material/button';
import {MatCardModule} from '@angular/material/card';
import {MatIconModule} from '@angular/material/icon';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatInputModule} from '@angular/material/input';
import {RouterLink} from '@angular/router';

@Component({selector:'app-about-page',standalone:true,imports:[RouterLink,MatButtonModule,MatIconModule],template:`<section class="page-hero page-pad"><span class="eyebrow">About EatHealthy</span><h1>Good health starts with a plan you can keep.</h1><p>We built EatHealthy for people who want practical guidance without expensive ingredients, confusing rules or a permanent AI bill.</p></section><section class="content-grid page-pad"><article><mat-icon>psychology_alt</mat-icon><h2>Explainable by design</h2><p>Suggestions come from transparent food, budget and nutrition rules. You can see why a meal fits.</p></article><article><mat-icon>diversity_1</mat-icon><h2>Built around real routines</h2><p>Commutes, family meals, pantry staples and South African budgets belong in the plan.</p></article><article><mat-icon>health_and_safety</mat-icon><h2>Wellness, responsibly</h2><p>EatHealthy supports general wellness and directs clinical needs to registered professionals.</p></article></section><section class="cta-band"><h2>Start with the food you already know.</h2><a mat-flat-button routerLink="/register">Build my profile</a></section>`}) export class AboutPageComponent{}

@Component({selector:'app-pricing-page',standalone:true,imports:[RouterLink,MatButtonModule,MatIconModule,MatCardModule],template:`<section class="page-hero page-pad"><span class="eyebrow">Simple pricing</span><h1>Start free. Upgrade when you need more support.</h1><p>No surprise charges. Payment integration remains in test mode until subscriptions launch.</p></section><section class="pricing-grid page-pad"><mat-card><mat-card-header><mat-card-title>Free</mat-card-title></mat-card-header><mat-card-content><h2>R0</h2><p>Meal planner, calorie estimates and a seven-day schedule.</p><ul><li>Budget-aware suggestions</li><li>Shopping list</li><li>Recipe video links</li></ul></mat-card-content><mat-card-actions><a mat-stroked-button routerLink="/register">Get started</a></mat-card-actions></mat-card><mat-card class="featured"><span class="plan-badge">MOST POPULAR</span><mat-card-header><mat-card-title>Plus</mat-card-title></mat-card-header><mat-card-content><h2>R79<small>/month</small></h2><p>Longer plans, reminders, reports and progress tracking.</p><ul><li>14-day schedules</li><li>Weight check-ins</li><li>Weekly and monthly reports</li></ul></mat-card-content><mat-card-actions><a mat-flat-button routerLink="/register">Start with Plus</a></mat-card-actions></mat-card><mat-card><mat-card-header><mat-card-title>Guided</mat-card-title></mat-card-header><mat-card-content><h2>Coming soon</h2><p>Connected support from dietitians and wellness professionals.</p><ul><li>Professional directory</li><li>Consultation referrals</li><li>Shared progress insights</li></ul></mat-card-content></mat-card></section>`}) export class PricingPageComponent{}

@Component({selector:'app-contact-page',standalone:true,imports:[MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule],template:`<section class="page-hero page-pad"><span class="eyebrow">Contact us</span><h1>Questions, feedback or partnership ideas?</h1><p>Tell us how EatHealthy can better support your wellness journey.</p></section><section class="contact-layout page-pad"><div class="contact-card"><mat-icon>mail</mat-icon><h2>Email</h2><p>hello@eathealthy.co.za</p><mat-icon>schedule</mat-icon><h2>Response time</h2><p>Usually within two working days.</p></div><form class="surface-form" (submit)="$event.preventDefault()"><mat-form-field appearance="outline"><mat-label>Name</mat-label><input matInput></mat-form-field><mat-form-field appearance="outline"><mat-label>Email</mat-label><input matInput type="email"></mat-form-field><mat-form-field appearance="outline"><mat-label>How can we help?</mat-label><textarea matInput rows="6"></textarea></mat-form-field><button mat-flat-button type="submit">Send message</button></form></section>`}) export class ContactPageComponent{}
